baseURL = "https://shuntarohata.github.io/RunningLog/"
title = "Running Log"
theme = "PaperMod"
languageCode = "ja"
relativeURLs = false
canonifyURLs = false

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]  # ← ここがポイント
  [params.homeInfoParams]
    Title = "出張先ランニングログ"
    Content = "海外出張中に走った記録"