baseURL = "https://shuntarohata.github.io/RunningLog/"
relativeURLs = false
canonifyURLs = false
theme = "PaperMod"
languageCode = "ja"

[pagination]
  pagerSize = 10

[params]
  [params.homeInfoParams]
    Title = "出張先ランニングログ"
    Content = "海外出張中に走った記録"
